AWSTemplateFormatVersion: '2010-09-09'
Mappings:
  RegionMap:
    ap-south-1:
      zookeeper-ami: ami-0809f544f4823a3a0
      clickhouse-ami: ami-0d12b9139d3490271
    eu-north-1:
      zookeeper-ami: ami-09fc4efac65948697
      clickhouse-ami: ami-04ebc80fe24e85734
    eu-west-3:
      zookeeper-ami: ami-03ca5c2aa466c383c
      clickhouse-ami: ami-00a05cd5851918906
    eu-west-2:
      zookeeper-ami: ami-04bd48d131d3f2539
      clickhouse-ami: ami-0785957fddcc0d2aa
    eu-west-1:
      zookeeper-ami: ami-05262f77f4a58627b
      clickhouse-ami: ami-091111613f8008808
    ap-northeast-3:
      zookeeper-ami: ami-062b1b56757905e68
      clickhouse-ami: ami-0e4b2c29fe8159a81
    ap-northeast-2:
      zookeeper-ami: ami-0afe4e17974ec8899
      clickhouse-ami: ami-02d3409151147f9c5
    ap-northeast-1:
      zookeeper-ami: ami-0feb004f34fbeb54b
      clickhouse-ami: ami-0f9b54ee6703ca6ce
    ca-central-1:
      zookeeper-ami: ami-08b099378355c22e3
      clickhouse-ami: ami-07491d6fa2a0be77b
    sa-east-1:
      zookeeper-ami: ami-0ff03ff99bb749a43
      clickhouse-ami: ami-044e5376596be446a
    ap-southeast-1:
      zookeeper-ami: ami-01f3d80c3cb33ce1f
      clickhouse-ami: ami-00e5a7d31928e4c50
    ap-southeast-2:
      zookeeper-ami: ami-0bf48169eb245e48b
      clickhouse-ami: ami-0009d5237bf2761d5
    eu-central-1:
      zookeeper-ami: ami-0a560a935e9c50540
      clickhouse-ami: ami-05bfa434ebc0e3d64
    us-east-1:
      zookeeper-ami: ami-0ecb3ad5c6fa31e13
      clickhouse-ami: ami-0d38a7a8a915f695e
    us-east-2:
      zookeeper-ami: ami-0573190c8d06c5e52
      clickhouse-ami: ami-0fdfa72a5786c34b0
    us-west-1:
      zookeeper-ami: ami-0026a926c44ea96be
      clickhouse-ami: ami-03dcc7f50fa64ec73
    us-west-2:
      zookeeper-ami: ami-07f65c3bfa8f128d0
      clickhouse-ami: ami-0e51d01a6edba187e






Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    # Notice how you can't attach an IGW to a VPC unless both are created:
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.10.0/24
      AvailabilityZone: !Select [ 0, !GetAZs ]    # Get the first AZ in the list
      MapPublicIpOnLaunch: true       
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Public-A 
  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.20.0/24
      AvailabilityZone: !Select [ 1, !GetAZs ]    # Get the second AZ in the list 
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Public-B
  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.50.0/24
      AvailabilityZone: !Select [ 0, !GetAZs ]    # Get the first AZ in the list 
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Private-A
  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.60.0/24
      AvailabilityZone: !Select [ 1, !GetAZs ]    # Get the second AZ in the list 
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Private-B      
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: Public
  PublicRoute1:   # Public route table has direct routing to IGW:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  NATGateway:
   Type: AWS::EC2::NatGateway
   Properties:
     AllocationId: !GetAtt ElasticIPAddress.AllocationId
     SubnetId: !Ref PublicSubnetA
     Tags:
     - Key: Name
       Value: !Sub NAT-${AWS::StackName}
  ElasticIPAddress:
   Type: AWS::EC2::EIP
   Properties:
     Domain: VPC
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: Private
  PrivateRoute1:            # Private route table can access web via NAT (created below)
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      # Route traffic through the NAT Gateway:
      NatGatewayId: !Ref NATGateway
  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable
  PublicSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref PublicRouteTable
  PrivateSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref PrivateRouteTable
  PrivateSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetB
      RouteTableId: !Ref PrivateRouteTable
  BastionHostSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH from 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0  
      VpcId: !Ref VPC
  ClickhouseSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP from 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '9000'
          ToPort: '9000'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0  
      VpcId: !Ref VPC    
  ZookeeperSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP from 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '2181'
          ToPort: '2181'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '2888'
          ToPort: '2888'
          CidrIp: 0.0.0.0/0  
        - IpProtocol: tcp
          FromPort: '3888'
          ToPort: '3888'
          CidrIp: 0.0.0.0/0    
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0  
      VpcId: !Ref VPC
  BastionHostNetworkInterface1:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !Ref PublicSubnetA
      GroupSet: 
        - !Ref BastionHostSecurityGroup
  BastionHost: 
    Type: AWS::EC2::Instance
    DependsOn: BastionHostNetworkInterface1
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "zookeeper-ami"]

      InstanceType: t2.micro
      NetworkInterfaces: 
        - NetworkInterfaceId: !Ref BastionHostNetworkInterface1
          DeviceIndex: "0"
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: 30
            DeleteOnTermination: true
            Encrypted: true    
      Tags:
       - Key: Name
         Value: bastion-host
  
  
  ZookeeperNetworkInterface1:
    DependsOn: ZookeeperNetworkInterface2
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !Ref PublicSubnetA
      GroupSet: 
        - !Ref ZookeeperSecurityGroup       
  ZookeeperEc2Instance1: 
    Type: AWS::EC2::Instance
    DependsOn: ZookeeperNetworkInterface1
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "zookeeper-ami"]

      InstanceType: t2.small
      UserData:
        Fn::Base64 : !Sub 
          - |
            #!/bin/bash -xe
            echo "hello-world"
            sudo sed -i -r "s/server-1-ip/0.0.0.0/" /usr/local/zookeeper/conf/zoo.cfg
            sudo sed -i -r "s/server-2-ip/${server_2}/" /usr/local/zookeeper/conf/zoo.cfg
            sudo sed -i -r "s/server-3-ip/${server_3}/" /usr/local/zookeeper/conf/zoo.cfg
            sudo ZK_SERVER_HEAP=128 /usr/local/zookeeper/bin/zkServer.sh start
          - server_2: !GetAtt ZookeeperNetworkInterface2.PrimaryPrivateIpAddress
            server_3: !GetAtt ZookeeperNetworkInterface3.PrimaryPrivateIpAddress
      NetworkInterfaces: 
        - NetworkInterfaceId: !Ref ZookeeperNetworkInterface1
          DeviceIndex: "0"
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: 30
            DeleteOnTermination: true
            Encrypted: true    
         
    
      Tags:
       - Key: Name
         Value: zookeeper-1
  

  ZookeeperNetworkInterface2:
    Type: AWS::EC2::NetworkInterface
    DependsOn: ZookeeperNetworkInterface3
    Properties:
      SubnetId: !Ref PublicSubnetB
      GroupSet: 
        - !Ref ZookeeperSecurityGroup
  
  ZookeeperEc2Instance2: 
    Type: AWS::EC2::Instance
    DependsOn: ZookeeperNetworkInterface2
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "zookeeper-ami"]

      InstanceType: t2.small
      UserData:
        Fn::Base64 : !Sub 
          - |
            #!/bin/bash -xe
            echo "hello-world"
            sudo sed -i -r "s/server-1-ip/${server_1}/" /usr/local/zookeeper/conf/zoo.cfg
            sudo sed -i -r "s/server-2-ip/0.0.0.0/" /usr/local/zookeeper/conf/zoo.cfg
            sudo sed -i -r "s/server-3-ip/${server_3}/" /usr/local/zookeeper/conf/zoo.cfg
            sudo sed -i -r "s/1/2/" /var/lib/zookeeper/myid
            sudo ZK_SERVER_HEAP=128 /usr/local/zookeeper/bin/zkServer.sh start
          - server_1: !GetAtt ZookeeperNetworkInterface1.PrimaryPrivateIpAddress
            server_3: !GetAtt ZookeeperNetworkInterface3.PrimaryPrivateIpAddress
            
      NetworkInterfaces: 
        - NetworkInterfaceId: !Ref ZookeeperNetworkInterface2
          DeviceIndex: "0"
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: 30
            DeleteOnTermination: true
            Encrypted: true  
         
          
      Tags:
       - Key: Name
         Value: zookeeper-2                           
  ZookeeperNetworkInterface3:

    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !Ref PublicSubnetA
      GroupSet: 
        - !Ref ZookeeperSecurityGroup
  
  
  ZookeeperEc2Instance3: 
    Type: AWS::EC2::Instance
    DependsOn: ZookeeperNetworkInterface3
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "zookeeper-ami"]

      InstanceType: t2.small
      UserData:
        Fn::Base64 : !Sub 
          - |
            #!/bin/bash -xe
            echo "hello-world"
            sudo sed -i -r "s/server-1-ip/${server_1}/" /usr/local/zookeeper/conf/zoo.cfg
            sudo sed -i -r "s/server-2-ip/${server_2}/" /usr/local/zookeeper/conf/zoo.cfg
            sudo sed -i -r "s/server-3-ip/0.0.0.0/" /usr/local/zookeeper/conf/zoo.cfg
            sudo sed -i -r "s/1/3/" /var/lib/zookeeper/myid
            sudo ZK_SERVER_HEAP=128 /usr/local/zookeeper/bin/zkServer.sh start
          - server_2: !GetAtt ZookeeperNetworkInterface2.PrimaryPrivateIpAddress
            server_1: !GetAtt ZookeeperNetworkInterface1.PrimaryPrivateIpAddress
      NetworkInterfaces: 
        - NetworkInterfaceId: !Ref ZookeeperNetworkInterface3
          DeviceIndex: "0"
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: 30
            DeleteOnTermination: true
            Encrypted: true    
      Tags:
       - Key: Name
         Value: zookeeper-3
  Ec2NetworkInterfaceClickhouse1:
    DependsOn: ZookeeperEc2Instance1
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !Ref PrivateSubnetA
      GroupSet: 
        - !Ref ClickhouseSecurityGroup
  EC2InstanceClickhouse1: 
    Type: AWS::EC2::Instance
    DependsOn: Ec2NetworkInterfaceClickhouse1
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "clickhouse-ami"]

      InstanceType: t2.small
      UserData:
        Fn::Base64 : !Sub 
          - |
            #!/bin/bash -xe
            echo "hello-world"
            sudo sed -i -r "s/shard-1-replica-1/${server_1}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/shard-2-replica-1/${server_2}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/shard-3-replica-1/${server_3}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/zookeeper-1-host/${z_1}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/zookeeper-2-host/${z_2}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/zookeeper-3-host/${z_3}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/shard-num/${s_num}/" /etc/clickhouse-server/config.d/macros.xml
            sudo sed -i -r "s/replica-num/${r_num}/" /etc/clickhouse-server/config.d/macros.xml
            sudo systemctl restart clickhouse-server
          - server_1: !GetAtt Ec2NetworkInterfaceClickhouse1.PrimaryPrivateIpAddress
            server_2: !GetAtt Ec2NetworkInterfaceClickhouse2.PrimaryPrivateIpAddress
            server_3: !GetAtt Ec2NetworkInterfaceClickhouse3.PrimaryPrivateIpAddress
            z_1: !GetAtt ZookeeperEc2Instance1.PrivateDnsName
            z_2: !GetAtt ZookeeperEc2Instance2.PrivateDnsName
            z_3: !GetAtt ZookeeperEc2Instance3.PrivateDnsName
            s_num: 1
            r_num: 1


      NetworkInterfaces: 
        - NetworkInterfaceId: !Ref Ec2NetworkInterfaceClickhouse1
          DeviceIndex: "0"
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: 30
            DeleteOnTermination: true
            Encrypted: true    
      Tags:
       - Key: Name
         Value: clickhouse-1      

  Ec2NetworkInterfaceClickhouse2:
    DependsOn: Ec2NetworkInterfaceClickhouse1
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !Ref PrivateSubnetB
      GroupSet: 
        - !Ref ClickhouseSecurityGroup
  EC2InstanceClickhouse2: 
    Type: AWS::EC2::Instance
    DependsOn: EC2InstanceClickhouse1
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "clickhouse-ami"]

      InstanceType: t2.small
      UserData:
        Fn::Base64 : !Sub 
          - |
            #!/bin/bash -xe
            echo "hello-world"
            sudo sed -i -r "s/shard-1-replica-1/${server_1}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/shard-2-replica-1/${server_2}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/shard-3-replica-1/${server_3}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/zookeeper-1-host/${z_1}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/zookeeper-2-host/${z_2}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/zookeeper-3-host/${z_3}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/shard-num/${s_num}/" /etc/clickhouse-server/config.d/macros.xml
            sudo sed -i -r "s/replica-num/${r_num}/" /etc/clickhouse-server/config.d/macros.xml
            sudo systemctl restart clickhouse-server
          - server_1: !GetAtt Ec2NetworkInterfaceClickhouse1.PrimaryPrivateIpAddress
            server_2: !GetAtt Ec2NetworkInterfaceClickhouse2.PrimaryPrivateIpAddress
            server_3: !GetAtt Ec2NetworkInterfaceClickhouse3.PrimaryPrivateIpAddress
            z_1: !GetAtt ZookeeperEc2Instance1.PrivateDnsName
            z_2: !GetAtt ZookeeperEc2Instance2.PrivateDnsName
            z_3: !GetAtt ZookeeperEc2Instance3.PrivateDnsName
            s_num: 2
            r_num: 1


      NetworkInterfaces: 
        - NetworkInterfaceId: !Ref Ec2NetworkInterfaceClickhouse2
          DeviceIndex: "0"
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: 30
            DeleteOnTermination: true
            Encrypted: true    
      Tags:
       - Key: Name
         Value: clickhouse-2   
  Ec2NetworkInterfaceClickhouse3:
    DependsOn: Ec2NetworkInterfaceClickhouse2
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !Ref PrivateSubnetA
      GroupSet: 
        - !Ref ClickhouseSecurityGroup         
  EC2InstanceClickhouse3: 
    Type: AWS::EC2::Instance
    DependsOn: EC2InstanceClickhouse2
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "clickhouse-ami"]

      InstanceType: t2.small
      UserData:
        Fn::Base64 : !Sub 
          - |
            #!/bin/bash -xe
            echo "hello-world"
            sudo sed -i -r "s/shard-1-replica-1/${server_1}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/shard-2-replica-1/${server_2}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/shard-3-replica-1/${server_3}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/zookeeper-1-host/${z_1}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/zookeeper-2-host/${z_2}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/zookeeper-3-host/${z_3}/" /etc/clickhouse-server/config.d/cluster.xml
            sudo sed -i -r "s/shard-num/${s_num}/" /etc/clickhouse-server/config.d/macros.xml
            sudo sed -i -r "s/replica-num/${r_num}/" /etc/clickhouse-server/config.d/macros.xml
            sudo systemctl restart clickhouse-server
          - server_1: !GetAtt Ec2NetworkInterfaceClickhouse1.PrimaryPrivateIpAddress
            server_2: !GetAtt Ec2NetworkInterfaceClickhouse2.PrimaryPrivateIpAddress
            server_3: !GetAtt Ec2NetworkInterfaceClickhouse3.PrimaryPrivateIpAddress
            z_1: !GetAtt ZookeeperEc2Instance1.PrivateDnsName
            z_2: !GetAtt ZookeeperEc2Instance2.PrivateDnsName
            z_3: !GetAtt ZookeeperEc2Instance3.PrivateDnsName
            s_num: 3
            r_num: 1


      NetworkInterfaces: 
        - NetworkInterfaceId: !Ref Ec2NetworkInterfaceClickhouse3
          DeviceIndex: "0"
      Tags:
       - Key: Name
         Value: clickhouse-3          

  

Outputs:
  VpcId:
    Description: Id of the vpc created by cloudformation
    Value: !GetAtt VPC.VpcId
  ClickhouseDnsHost:
    Description: public dns of the ec2 instance
    Value:  !GetAtt EC2InstanceClickhouse3.PrivateDnsName
  PublicSubNetAId:
    Description: Id of public subnet A
    Value: !GetAtt PublicSubnetA.SubnetId
  PublicSubNetBId:
    Description: Id of public subnet b
    Value: !GetAtt PublicSubnetB.SubnetId
  PrivateSubNetAId:
    Description: Id of private subnet A
    Value: !GetAtt PrivateSubnetA.SubnetId
  PrivateSubNetBId:
    Description: Id of public subnet A
    Value: !GetAtt PrivateSubnetB.SubnetId            

