signoz-app:
  existing-vpc: "no"
  otel-service-name: "otel"
  query-servcice-name: "query"
  alert-service-name: "alert"
  frontend-service-name: "frontend"
  clickhouse-host-name: ""
  environment-name: "dev"
  application-name: "my-signoz"
  clickhouse-stack-name: "clickhouse"
  zookeeper-disk-size: 30
  clickhouse-disk-size: 30
  zookeeper-instance-type: "t2.small"
  clickhouse-instance-type: "t2.small"
  fluentbit-repo-name: "fluentbit-repository"
  fluentbit-local-image-name: "custom-fluent"
  fluentbit-image-url: ""
  public-subnet-a-id: ""
  public-subnet-b-id: ""
  private-subnet-a-id: ""
  private-subnet-b-id: ""
  vpc-id: ""
  otel-service-endpoint: ""
