signoz-app:
  existing-vpc: "no"
  otel-service-name: "otel"
  query-servcice-name: "query"
  alert-service-name: "alert"
  frontend-service-name: "frontend"
  clickhouse-host-name: ""
  environment-name: "dev"
  application-name: "signoz-deploy-delta"
  clickhouse-stack-name: "clickhouse-signoz-3"
  zookeeper-disk-size: 30
  clickhouse-disk-size: 30
  zookeeper-instance-type: "t2.small"
  clickhouse-instance-type: "t2.small"
  fluentbit-repo-name: "fluentbit-repository-2"
  fluentbit-local-image-name: "custom-fluent-23"
  fluentbit-image-url: "511522223657.dkr.ecr.ap-south-1.amazonaws.com/fluentbit-repository-2"
  public-subnet-a-id: "subnet-04bcbde67eae92dc2"
  public-subnet-b-id: "subnet-0f38cdb0a50798ff2"
  private-subnet-a-id: "subnet-09f310755773d0f3c"
  private-subnet-b-id: "subnet-048adeca630ffcfba"
  vpc-id: "vpc-02f50b8b34b21dec6"
  otel-service-endpoint: "otel-svc.dev.signoz-deploy-delta-app.local"
