# signoz-app:
#   existing-vpc: "yes"
#   more-az: "false"
#   otel-service-name: "otel"
#   query-servcice-name: "query"
#   alert-service-name: "alert"
#   frontend-service-name: "frontend"
#   clickhouse-host-name: "ip-10-1-70-66.ap-southeast-1.compute.internal"
#   environment-name: "dev"
#   application-name: "signoz-deploy"
#   clickhouse-stack-name: "clickhouse-ex"
#   zookeeper-disk-size: 30
#   clickhouse-disk-size: 30
#   zookeeper-instance-type: "t2.small"
#   clickhouse-instance-type: "t2.small"
#   fluentbit-repo-name: "fluentbit-repository-3"
#   fluentbit-local-image-name: "custom-fluent-233"
#   fluentbit-image-url: "511522223657.dkr.ecr.ap-southeast-1.amazonaws.com/fluentbit-repository-3"
#   public-subnet-a-id: "subnet-031b781a4835d5b0f"
#   public-subnet-b-id: "subnet-08146945656dce1d0"
#   private-subnet-a-id: "subnet-08f15d24e1095fbfe"
#   private-subnet-b-id: "subnet-08b9dc72185cd90b4"
#   vpc-id: "vpc-0e6c48945f3376d3e"
#   otel-service-endpoint: "otel-svc.dev-signoz.signoz-deploy-app.local"
signoz-app:
  application-name: "gt-signoz-1"
  environment-name: "dev"
  clickhouseConf:
    stackName: "gt-signoz-1"
    clickhouseDiskSize: 30
    zookeeperDiskSize: 30
    zookeeperInstanceType: "t2.small"
    instanceType: "t2.small"
    hostName:
  fluentbitConf:
    repoName: "fbit-repo"
    localImageName: "fbit"
  otelSidecarConf:
    repoName: "sidecar-otel"
    localImageName: "sotel"
  serviceNames:
    otel: "otel"
    query: "query"
    alert: "alert"
    frontend: "frontend"
  # existingVpc:
  #   vpcId: vpc-09cc39b8b0fa6b10f
  #   publicSubnetAId: subnet-0787b5ad8b2d8aa41
  #   publicSubnetBId: subnet-07d3d63b9c87501b0
  #   privateSubnetAId: subnet-05870291afed3115e
  #   privateSubnetBId: subnet-045544de09bff69be
